<a href="https://www.kaggle.com/code/bhavinmoriya/pandas-exercise?scriptVersionId=109298155" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Pandas Exercises

Time to test your new pandas skills! Use the two csv files in this folder to complete the tasks in bold below!

** NOTE: ALL TASKS MUST BE DONE IN ONE LINE OF PANDAS CODE. GOT STUCK? NO PROBLEM! CHECK OUT THE SOLUTIONS LECTURE! **

** Import pandas and read in the banklist.csv file into a dataframe called banks. **

In [1]:
import pandas as pd

In [2]:
banks = pd.read_csv('../input/banklist/banklist.csv')

** Show the head of the dataframe **

In [3]:
# CODE HERE
banks.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,1-Jun-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,1-Jun-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,23-May-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17

** What are the column names? **

In [4]:
# CODE HERE
banks.columns

Index(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'],
      dtype='object')

** How many States (ST) are represented in this data set? **

In [5]:
# CODE HERE
banks['ST'].nunique()

44

** Get a list or array of all the states in the data set. **

In [6]:
# CODE HERE
banks['ST'].unique()

array(['IL', 'WI', 'LA', 'UT', 'NJ', 'AR', 'GA', 'PA', 'TN', 'WA', 'CO',
       'PR', 'FL', 'MN', 'CA', 'MD', 'OK', 'OH', 'SC', 'VA', 'ID', 'TX',
       'CT', 'AZ', 'NV', 'NC', 'KY', 'MO', 'KS', 'AL', 'MI', 'IN', 'IA',
       'NE', 'MS', 'NM', 'OR', 'NY', 'MA', 'SD', 'WY', 'WV', 'NH', 'HI'],
      dtype=object)

** What are the top 5 states with the most failed banks? **

In [7]:
# CODE HERE
banks.groupby(by='ST').count().sort_values(by='Bank Name', ascending=False).iloc[:5,1]

ST
GA    93
FL    75
IL    67
CA    41
MN    23
Name: City, dtype: int64

** What are the top 5 acquiring institutions? **

In [8]:
# CODE HERE
banks.groupby('Acquiring Institution').count().sort_values(by='City', ascending=False).iloc[:5,1]

Acquiring Institution
No Acquirer                            31
State Bank and Trust Company           12
First-Citizens Bank & Trust Company    11
Ameris Bank                            10
U.S. Bank N.A.                          9
Name: City, dtype: int64

** How many banks has the State Bank of Texas acquired? How many of them were actually in Texas?**

In [9]:
# CODE HERE
banks[(banks['Acquiring Institution'] == 'State Bank of Texas') & (banks['ST'] ==  'TX')]
# banks

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
450,Millennium State Bank of Texas,Dallas,TX,57667,State Bank of Texas,2-Jul-09,26-Oct-12

** What is the most common city in California for a bank to fail in?**

In [10]:
# CODE HERE
banks[banks['ST'] == 'CA'].groupby('City').count().sort_values(by='ST', ascending=False).head(1)

,Bank Name,ST,CERT,Acquiring Institution,Closing Date,Updated Date
City,,,,,,
Los Angeles,4,4,4,4,4,4

** How many failed banks don't have the word "Bank" in their name? **

In [11]:
# CODE HERE
banks[banks['Bank Name'].apply(lambda x:'Bank' not in x)].shape[0]

14

** How many bank names start with the letter 's' ? **

In [12]:
# CODE HERE
banks[banks['Bank Name'].apply(lambda x:x[0].lower() == 's')].shape[0]

53

** How many CERT values are above 20000 ? **

In [13]:
# CODE HERE
banks[banks['CERT'] > 20000].shape[0]

417

** How many bank names consist of just two words? (e.g. "First Bank" , "Bank Georgia" )**

In [14]:
# CODE HERE
banks[banks['Bank Name'].apply(lambda x:len(x.split())==2)].shape[0]

114

**Bonus: How many banks closed in the year 2008? (this is hard because we technically haven't learned about time series with pandas yet! Feel free to skip this one!**

In [15]:
# CODE HERE
banks[banks['Closing Date'].apply(lambda x:x[-2:]=='08')].shape[0]

25

# GREAT JOB!